server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      buffered: false
      suffix:
      file-date-format:

logging:
  level:
    raj: DEBUG

zuul:
  routes:
    auth-center:
      path: /login/**
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false
    backend-service:
      path: /backend/**

raj.security.jwt.secret: asupersecretpassword
